//产品数据信息
var mainProductListData={
    mainProductList:[
        {
            sceneId:4,
            name:"逆变器",
            productList:[
                {
                    name:"SUN2000-36KTL",
                    modelDesc:"SUN2000-36KTL型号说明性文字",
                    taskList:[
                        {
                            name:"在售",
                            desc:"时间是九月中旬xxxxxxxx",
                            date:"2017-09-15",
                            dataDesc:"9月中旬",
                            state:"warning"
                        },
                        {
                            name:"切换XXX",
                            desc:"时间是五月中旬xxxxxxxx",
                            date:"2018-05-05",
                            dataDesc:"5月初",
                            state:"warning"
                        },
                        {
                            name:"test1",
                            desc:"时间是五月中旬xxxxxxxx",
                            date:"2017-11-05",
                            dataDesc:"11月初",
                            state:"warning"
                        },
                        {
                            name:"test2",
                            desc:"时间是五月中旬xxxxxxxx",
                            date:"2017-11-15",
                            dataDesc:"11月初",
                            state:"warning",
                            position: "top"
                        },
                        {
                            name:"test3",
                            desc:"时间是五月中旬xxxxxxxx",
                            date:"2017-11-25",
                            dataDesc:"11月初",
                            state:"warning"
                        },
                        {
                            name:"测试1",
                            desc:"时间是五月中旬xxxxxxxx",
                            date:"2018-02-01",
                            dataDesc:"2月初",
                            state:"delayed"
                        },
                        {
                            name:"测试2",
                            desc:"时间是五月中旬xxxxxxxx",
                            date:"2018-02-15",
                            dataDesc:"2月中旬",
                            state:"delayed",
                            position: "top"
                        },
                        {
                            name:"测试3",
                            desc:"时间是五月中旬xxxxxxxx",
                            date:"2018-02-25",
                            dataDesc:"2月下旬",
                            state:"delayed"
                        }
                    ]
                },
                {
                    name:"型号B",
                    modelDesc:"型号B说明性文字",
                    taskList:[
                        {
                            name:"TR5",
                            desc:"生产需要延期，预估延期到11月",
                            date:"2017-09-15",
                            dataDesc:"10月上旬",
                            state:"delayed "
                        },
                        {
                            name:"入网验证",
                            desc:"入网验证小说明小说明",
                            date:"2017-12-05",
                            dataDesc:"12月初",
                            state:"normal"
                        },
                        {
                            name:"BETA验证",
                            desc:"BETA验证说明说明说明",
                            date:"2018-01-10",
                            dataDesc:"1月初",
                            state:"normal"
                        },
                        {
                            name:"BETA验证",
                            desc:"BETA验证说明说明说明2",
                            date:"2018-03-01",
                            dataDesc:"3月初",
                            state:"normal"
                        },
                        {
                            name:"限制销售",
                            desc:"限制销售说明说明说明",
                            date:"2018-03-15",
                            dataDesc:"3月中旬",
                            state:"normal",
                            position: "top"
                        },
                        {
                            name:"TR6",
                            desc:"TR6说明说明说明",
                            date:"2018-03-29",
                            dataDesc:"3月下旬",
                            state:"normal"
                        }
                    ]
                },
                {
                    name:"型号C",
                    modelDesc:"型号C说明性文字",
                    taskList:[
                        {
                            name:"标书引导",
                            desc:"标书引导说明说明",
                            date:"2017-10-10",
                            dataDesc:"10月上旬",
                            state:"normal"
                        },
                        {
                            name:"预警",
                            desc:"预警说明说明说明",
                            date:"2018-01-10",
                            dataDesc:"1月上旬",
                            state:"normal"
                        },
                        {
                            name:"TR6",
                            desc:"TR6说明说明说明说明",
                            date:"2018-04-05",
                            dataDesc:"4月上旬",
                            state:"normal"
                        },
                        {
                            name:"中标",
                            desc:"中标说明说明说明说明说明",
                            date:"2017-09-01",
                            dataDesc:"6月初",
                            state:"normal"
                        }
                    ]
                }
            ]

        },
        {
            sceneId:3,
            name:"数采",
            productList:[
                {
                    name:"SUN2000-36KTL",
                    modelDesc:"SUN2000-36KTL说明性文字",
                    taskList:[
                        {
                            name:"在售",
                            desc:"时间是九月中旬xxxxxxxx",
                            date:"2017-09-15",
                            dataDesc:"9月中旬",
                            state:"warning"
                        },
                        {
                            name:"切换XXX",
                            desc:"时间是五月中旬xxxxxxxx",
                            date:"2018-05-05",
                            dataDesc:"5月初",
                            state:"delayed"
                        }
                    ]
                },
                {
                    name:"型号B",
                    modelDesc:"型号B说明性文字",
                    taskList:[
                        {
                            name:"TR5",
                            desc:"生产需要延期，预估延期到11月",
                            date:"2017-09-15",
                            dataDesc:"10月上旬",
                            state:"delayed "
                        },
                        {
                            name:"入网验证",
                            desc:"入网验证小说明小说明",
                            date:"2017-12-05",
                            dataDesc:"12月初",
                            state:"normal"
                        },
                        {
                            name:"BETA验证",
                            desc:"BETA验证说明说明说明",
                            date:"2018-01-10",
                            dataDesc:"1月初",
                            state:"normal"
                        },
                        {
                            name:"BETA验证",
                            desc:"BETA验证说明说明说明2",
                            date:"2018-03-01",
                            dataDesc:"3月初",
                            state:"normal"
                        },
                        {
                            name:"限制销售",
                            desc:"限制销售说明说明说明",
                            date:"2018-03-15",
                            dataDesc:"3月中旬",
                            state:"normal",
                            position: "top"
                        },
                        {
                            name:"TR6",
                            desc:"TR6说明说明说明",
                            date:"2018-03-29",
                            dataDesc:"3月下旬",
                            state:"normal"
                        }
                    ]
                },
                {
                    name:"型号C",
                    modelDesc:"型号C说明性文字",
                    taskList:[
                        {
                            name:"标书引导",
                            desc:"标书引导说明说明",
                            date:"2017-10-10",
                            dataDesc:"10月上旬",
                            state:"normal"
                        },
                        {
                            name:"预警",
                            desc:"预警说明说明说明",
                            date:"2018-01-10",
                            dataDesc:"1月上旬",
                            state:"normal"
                        },
                        {
                            name:"TR6",
                            desc:"TR6说明说明说明说明",
                            date:"2018-04-05",
                            dataDesc:"4月上旬",
                            state:"normal"
                        },
                        {
                            name:"中标",
                            desc:"中标说明说明说明说明说明",
                            date:"2017-09-01",
                            dataDesc:"6月初",
                            state:"normal"
                        }
                    ]
                }
            ]
        },
        {
            sceneId:3,
            name:"SACU",
            productList:[
                {
                    name:"SUN2000-36KTL",
                    modelDesc:"SUN2000-36KTL说明性文字",
                    taskList:[
                        {
                            name:"在售",
                            desc:"时间是九月中旬xxxxxxxx",
                            date:"2017-09-15",
                            dataDesc:"9月中旬",
                            state:"warning"
                        },
                        {
                            name:"切换XXX",
                            desc:"时间是五月中旬xxxxxxxx",
                            date:"2018-05-05",
                            dataDesc:"5月初",
                            state:"delayed"
                        }
                    ]
                },
                {
                    name:"型号B",
                    modelDesc:"型号B说明性文字",
                    taskList:[
                        {
                            name:"TR5",
                            desc:"生产需要延期，预估延期到11月",
                            date:"2017-09-15",
                            dataDesc:"10月上旬",
                            state:"delayed "
                        },
                        {
                            name:"入网验证",
                            desc:"入网验证小说明小说明",
                            date:"2017-12-05",
                            dataDesc:"12月初",
                            state:"normal"
                        },
                        {
                            name:"BETA验证",
                            desc:"BETA验证说明说明说明",
                            date:"2018-01-10",
                            dataDesc:"1月初",
                            state:"normal"
                        },
                        {
                            name:"BETA验证",
                            desc:"BETA验证说明说明说明2",
                            date:"2018-03-01",
                            dataDesc:"3月初",
                            state:"normal"
                        },
                        {
                            name:"限制销售",
                            desc:"限制销售说明说明说明",
                            date:"2018-03-15",
                            dataDesc:"3月中旬",
                            state:"normal",
                            position: "top"
                        },
                        {
                            name:"TR6",
                            desc:"TR6说明说明说明",
                            date:"2018-03-29",
                            dataDesc:"3月下旬",
                            state:"normal"
                        }
                    ]
                },
                {
                    name:"型号C",
                    modelDesc:"型号C说明性文字",
                    taskList:[
                        {
                            name:"标书引导",
                            desc:"标书引导说明说明",
                            date:"2017-10-10",
                            dataDesc:"10月上旬",
                            state:"normal"
                        },
                        {
                            name:"预警",
                            desc:"预警说明说明说明",
                            date:"2018-01-10",
                            dataDesc:"1月上旬",
                            state:"normal"
                        },
                        {
                            name:"TR6",
                            desc:"TR6说明说明说明说明",
                            date:"2018-04-05",
                            dataDesc:"4月上旬",
                            state:"normal"
                        },
                        {
                            name:"中标",
                            desc:"中标说明说明说明说明说明",
                            date:"2017-09-01",
                            dataDesc:"6月初",
                            state:"normal"
                        }
                    ]
                }
            ]
        },
        {
            sceneId:3,
            name:"管理系统",
            productList:[
                {
                    name:"SUN2000-36KTL",
                    modelDesc:"SUN2000-36KTL说明性文字",
                    taskList:[
                        {
                            name:"在售",
                            desc:"时间是九月中旬xxxxxxxx",
                            date:"2017-09-15",
                            dataDesc:"9月中旬",
                            state:"warning"
                        },
                        {
                            name:"切换XXX",
                            desc:"时间是五月中旬xxxxxxxx",
                            date:"2018-05-05",
                            dataDesc:"5月初",
                            state:"delayed"
                        }
                    ]
                },
                {
                    name:"型号B",
                    modelDesc:"型号B说明性文字",
                    taskList:[
                        {
                            name:"TR5",
                            desc:"生产需要延期，预估延期到11月",
                            date:"2017-09-15",
                            dataDesc:"10月上旬",
                            state:"delayed "
                        },
                        {
                            name:"入网验证",
                            desc:"入网验证小说明小说明",
                            date:"2017-12-05",
                            dataDesc:"12月初",
                            state:"normal"
                        },
                        {
                            name:"BETA验证",
                            desc:"BETA验证说明说明说明",
                            date:"2018-01-10",
                            dataDesc:"1月初",
                            state:"normal"
                        },
                        {
                            name:"BETA验证",
                            desc:"BETA验证说明说明说明2",
                            date:"2018-03-01",
                            dataDesc:"3月初",
                            state:"normal"
                        },
                        {
                            name:"限制销售",
                            desc:"限制销售说明说明说明",
                            date:"2018-03-15",
                            dataDesc:"3月中旬",
                            state:"normal",
                            position: "top"
                        },
                        {
                            name:"TR6",
                            desc:"TR6说明说明说明",
                            date:"2018-03-29",
                            dataDesc:"3月下旬",
                            state:"normal"
                        }
                    ]
                },
                {
                    name:"型号C",
                    modelDesc:"型号C说明性文字",
                    taskList:[
                        {
                            name:"标书引导",
                            desc:"标书引导说明说明",
                            date:"2017-10-10",
                            dataDesc:"10月上旬",
                            state:"normal"
                        },
                        {
                            name:"预警",
                            desc:"预警说明说明说明",
                            date:"2018-01-10",
                            dataDesc:"1月上旬",
                            state:"normal"
                        },
                        {
                            name:"TR6",
                            desc:"TR6说明说明说明说明",
                            date:"2018-04-05",
                            dataDesc:"4月上旬",
                            state:"normal"
                        },
                        {
                            name:"中标",
                            desc:"中标说明说明说明说明说明",
                            date:"2017-09-01",
                            dataDesc:"6月初",
                            state:"normal"
                        }
                    ]
                }
            ]
        }
    ]
};